# Generated by Django 2.0.2 on 2018-04-14 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Taken_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CancelAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Middle_Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Blood_Grp', models.CharField(max_length=8)),
                ('Degree', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Profile_pic', models.FileField(upload_to='profilepics/')),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('m1_days', models.CharField(max_length=100)),
                ('m1_times_a_day', models.CharField(max_length=100)),
                ('m2_days', models.CharField(max_length=100)),
                ('m2_times_a_day', models.CharField(max_length=100)),
                ('m3_days', models.CharField(max_length=100)),
                ('m3_times_a_day', models.CharField(max_length=100)),
                ('m4_days', models.CharField(max_length=100)),
                ('m4_times_a_day', models.CharField(max_length=100)),
                ('m5_days', models.CharField(max_length=100)),
                ('m5_times_a_day', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Middle_Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Blood_Grp', models.CharField(max_length=8)),
                ('Profile_pic', models.FileField(upload_to='profilepics/')),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Time', models.CharField(max_length=15)),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Middle_Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Blood_Grp', models.CharField(max_length=8)),
                ('Date_of_joining', models.DateField()),
                ('Profile_pic', models.FileField(upload_to='profilepics/')),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Time', models.TimeField()),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='historydata',
            name='Med_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m1', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='historydata',
            name='Med_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='historydata',
            name='Med_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m3', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='historydata',
            name='Med_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m4', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='historydata',
            name='Med_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m5', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='historydata',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelappointments',
            name='Doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Doctor'),
        ),
        migrations.AddField(
            model_name='cancelappointments',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Slot_Time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Slots'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
