# Generated by Django 2.0.2 on 2018-04-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historydata_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='Med_2',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='Med_3',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='Med_4',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='Med_5',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m2_days',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m2_times_a_day',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m3_days',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m3_times_a_day',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m4_days',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m4_times_a_day',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m5_days',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='m5_times_a_day',
        ),
    ]
