# Generated by Django 2.0.2 on 2018-04-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180414_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='Med_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.medicine'),
        ),
    ]
