# Generated by Django 2.0.2 on 2018-04-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180415_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='Doctor_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
